#!/usr/bin/python3

import sys

def factorize_numbers(input_file):
    with open(input_file) as file:
        for line in file:
            number = int(line)
            if number % 2 == 0:
                print("{}={}*{}".format(number, number // 2, 2))
                continue
            divisor = 3
            while divisor <= number // 2:
                if number % divisor == 0:
                    print("{}={}*{}".format(number, number // divisor, divisor))
                    break
                divisor += 2
            if divisor > number // 2:
                print("{}={}*{}".format(number, number, 1))

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: {} <file>".format(sys.argv[0]))
        sys.exit(1)
    
    input_file = sys.argv[1]
    factorize_numbers(input_file)
