#!/usr/bin/python3
"""
Factorize as many numbers as possible into a product of two smaller numbers.

Usage: factors <file>
where <file> is a file containing natural numbers to factor.
One number per line
You can assume that all lines will be valid natural numbers greater than 1
You can assume that there will be no empty line, and no space before and after the valid number
The file will always end with a new line
Output format: n=p*q
one factorization per line
p and q don’t have to be prime numbers
See example
You can work on the numbers of the file in the order of your choice
Your program should run without any dependency: You will not be able to install anything on the machine we will run your program on
Time limit: Your program will be killed after 5 seconds if it hasn’t finished
Push all your scripts, source code, etc… to your repository
"""
# Import sys to get command-line arguments
import sys

def factorize_numbers():
    """
    Function to factorize numbers from a file and print the factorization.
    """
    try:
        input_file = sys.argv[1]
        with open(input_file) as file:
            for line in file:
                number = int(line)
                if number % 2 == 0:
                    print("{}={}*{}".format(number, number // 2, 2))
                    continue
                divisor = 3
                while divisor < number // 2:
                    if number % divisor == 0:
                        print("{}={}*{}".format(number, number // divisor, divisor))
                        break
                    divisor = divisor + 2
                if divisor == (number // 2) + 1:
                    print("{}={}*{}".format(number, number, 1))
    except IndexError:
        pass

# Start the factorization process
factorize_numbers()
